import Groq from "groq-sdk";
import { CycleLog } from "../models/cycleLogSchema.js";
import { User } from "../models/userSchema.js";
import { catchAsyncErrors } from "../middlewares/catchAsyncErrors.js";
import ErrorHandler from "../middlewares/error.js";

const RISK_PROMPT = `You are a menstrual health risk analyst AI embedded in a women's health platform called Syncora.

You will receive a user's profile and their last 3 months of cycle log data.
Your job is to analyze patterns and flag potential health risks — gently and responsibly.

IMPORTANT CONTEXT ON DATA:
- Users only log days when they have flow, symptoms, or mood changes — they do NOT log every single day of the month.
- 5–15 logged days over 3 months is completely normal and represents multiple full cycles worth of data.
- Judge data quality based on the number of distinct periods covered and the richness of symptom/mood data — NOT on raw day count.
- Only mark data_quality as "insufficient" if there are 0 logged days. Mark "limited" only if fewer than 3 days are logged.
- The user's profile fields (avg cycle length, period duration, last period date, known conditions) are rich data — use them heavily in your analysis even when log count is low.

Rules:
- NEVER diagnose. Say "may indicate" or "could be associated with" — never "you have".
- Be warm, not alarming. Frame risks as things to watch, not certainties.
- Always recommend consulting a gynaecologist for anything flagged moderate or high.

Respond ONLY with a valid JSON object, no markdown, no extra text:
{
  "data_quality": "good" | "limited" | "insufficient",
  "data_quality_message": "1 sentence about how much data was analyzed",
  "risks": [
    {
      "condition": "e.g. PCOS",
      "likelihood": "low" | "moderate" | "high",
      "reason": "1-2 sentences explaining what pattern was detected",
      "what_to_watch": "1 sentence — specific signs to monitor",
      "action": "1 sentence — what to do next",
      "learn_more": "1 sentence about this condition in simple language"
    }
  ],
  "positive_signs": [
    "1 sentence positive observation about their cycle data"
  ],
  "overall_summary": "2-3 sentence warm overall summary of their cycle health",
  "disclaimer": "This analysis is generated by AI based on self-reported data and is not a medical diagnosis. Please consult a qualified gynaecologist for any health concerns."
}`;

export const getRiskPrediction = catchAsyncErrors(async (req, res, next) => {
  const groqApiKey = process.env.GROQ_API_KEY?.trim();
  const groq = groqApiKey ? new Groq({ apiKey: groqApiKey }) : null;

  if (!groqApiKey || !groq) {
    return next(new ErrorHandler("GROQ_API_KEY is missing.", 500));
  }

  // ── 1. Fetch user profile ──────────────────────────────────
  const user = await User.findById(req.user._id).select(
    "age avgCycleLength cycleRegularity periodDuration lastPeriodStartDate Medical_Conditions currentMedications",
  );

  if (!user) {
    return next(new ErrorHandler("User not found.", 404));
  }

  // ── 2. Fetch last 3 months of logs ─────────────────────────
  const threeMonthsAgo = new Date();
  threeMonthsAgo.setMonth(threeMonthsAgo.getMonth() - 3);

  const logs = await CycleLog.find({
    user: req.user._id,
    date: { $gte: threeMonthsAgo },
  }).sort({ date: 1 });

  // ── 3. Summarise log data for the prompt ───────────────────
  const totalDaysLogged = logs.length;

  // Count flow days
  const flowDays = logs.filter((l) => l.flow && l.flow !== "none");
  const heavyFlowDays = flowDays.filter((l) => l.flow === "heavy").length;
  const mediumFlowDays = flowDays.filter((l) => l.flow === "medium").length;
  const lightFlowDays = flowDays.filter((l) => l.flow === "light").length;

  // Estimate distinct periods: group flow days that are within 2 days of each other
  let distinctPeriods = 0;
  let lastFlowDate = null;
  flowDays.forEach((l) => {
    const d = new Date(l.date);
    if (
      !lastFlowDate ||
      (d - lastFlowDate) / (1000 * 60 * 60 * 24) > 2
    ) {
      distinctPeriods++;
    }
    lastFlowDate = d;
  });

  // Collect all symptoms and count frequency
  const symptomCount = {};
  logs.forEach((l) => {
    l.symptoms.forEach((s) => {
      symptomCount[s] = (symptomCount[s] || 0) + 1;
    });
  });
  const topSymptoms = Object.entries(symptomCount)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 8)
    .map(([s, count]) => `${s} (${count} days)`);

  // Collect mood patterns
  const moodCount = {};
  logs.forEach((l) => {
    l.mood.forEach((m) => {
      moodCount[m] = (moodCount[m] || 0) + 1;
    });
  });
  const topMoods = Object.entries(moodCount)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([m, count]) => `${m} (${count} days)`);

  // ── 4. Build the user message ──────────────────────────────
  const userMessage = `
USER PROFILE:
- Age: ${user.age}
- Average cycle length: ${user.avgCycleLength || "not set"} days
- Cycle regularity: ${user.cycleRegularity || "not specified"}
- Period duration: ${user.periodDuration || "not set"} days
- Last period start date: ${user.lastPeriodStartDate ? user.lastPeriodStartDate.toDateString() : "not set"}
- Known medical conditions: ${user.Medical_Conditions?.length ? user.Medical_Conditions.join(", ") : "none reported"}
- Currently on medication: ${user.currentMedications ? "yes" : "no"}

CYCLE LOG SUMMARY (last 3 months):
- Note: Users only log days with flow/symptoms — not every calendar day. Low day counts are normal.
- Total days logged: ${totalDaysLogged} (these are active symptom/flow days, not total days in the period)
- Estimated distinct periods captured: ${distinctPeriods}
- Total flow days: ${flowDays.length} (light: ${lightFlowDays}, medium: ${mediumFlowDays}, heavy: ${heavyFlowDays})
- Most frequent symptoms: ${topSymptoms.length ? topSymptoms.join(", ") : "none logged"}
- Most frequent moods: ${topMoods.length ? topMoods.join(", ") : "none logged"}
  `.trim();

  // ── 5. Call Groq ───────────────────────────────────────────
  try {
    const completion = await groq.chat.completions.create({
      model: "llama-3.3-70b-versatile",
      messages: [
        { role: "system", content: RISK_PROMPT },
        { role: "user", content: userMessage },
      ],
      temperature: 0.3,
      max_completion_tokens: 1200,
    });

    const raw = completion.choices?.[0]?.message?.content?.trim() || "";

    if (!raw) {
      return next(
        new ErrorHandler("Could not generate analysis. Please try again.", 502),
      );
    }

    const cleaned = raw.replace(/```json|```/g, "").trim();

    let analysis;
    try {
      analysis = JSON.parse(cleaned);
    } catch {
      return next(
        new ErrorHandler(
          "AI response was not in expected format. Please try again.",
          502,
        ),
      );
    }

    res.status(200).json({ success: true, data: analysis });
  } catch (error) {
    const msg = String(error?.message || "");
    if (msg.includes("401") || msg.toLowerCase().includes("invalid api key")) {
      return next(new ErrorHandler("Groq API key is invalid.", 401));
    }
    if (msg.includes("429") || msg.toLowerCase().includes("rate limit")) {
      return next(
        new ErrorHandler("Too many requests. Please try again shortly.", 429),
      );
    }
    return next(
      new ErrorHandler(
        "Risk prediction service is temporarily unavailable.",
        502,
      ),
    );
  }
});